-- only attach doc
begin tran
 
declare @lcustomername engg_name
declare @lprojectname engg_name
declare @lcomponentname engg_name
declare @lecrno engg_name
declare @lguid engg_guid
 
set @lcustomername='BCDG'
set @lprojectname='7H118'
set @lcomponentname = 'HRMSPYSUP'
set @lecrno='PSU_ECR_00449'
set @lguid='FB6F1043-5F86-48F6-AC3F-BFEF52B0EEB2'
 
create table #fw_req_activity (activitydesc varchar(60) collate SQL_Latin1_General_CP1_CI_AS,activityid int,activityname varchar(60) collate SQL_Latin1_General_CP1_CI_AS,activityposition int, activitysequence int,activitytype int, iswfenabled int,ComponentName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_req_activity_ilbo (activityid int,ilbocode varchar(60) collate SQL_Latin1_General_CP1_CI_AS,activityname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime) 
create table #fw_req_ilbo (aspofilepath varchar(255) collate SQL_Latin1_General_CP1_CI_AS,description varchar(255) collate SQL_Latin1_General_CP1_CI_AS, ilbocode varchar(60) collate SQL_Latin1_General_CP1_CI_AS,ilbotype int,progid varchar(60) collate SQL_Latin1_General_CP1_CI_AS, statusflag int, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime, HasLegacyState varchar(2),HasRTState varchar(2), HasTree varchar(2), HasChart varchar(2), HasRichControl varchar(2), HasPivot varchar(2), HasContextDataItem varchar(2),HasDataSavingTask varchar(2) ,HasDataDrivenTask varchar(2), HasControlExtension varchar(2),hasmessagelookup varchar(2), HasMessageLookupPub varchar(2), HasDynamicLink varchar(2), HasBaseCallout varchar(2), HasTaskCallout varchar(2),HasPreTaskCallout varchar(2),HasPostTaskCallout varchar(2), HaseZeeView varchar(2), HasDynamicILBOTitle varchar(2),HasIlboPublished varchar(2),hasqlik varchar(2),sensitive varchar(1),HasUniversalPersonalization varchar(2))
create table #fw_req_activity_task (ActivityId varchar(60) collate SQL_Latin1_General_CP1_CI_AS, TaskName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, InvocationType tinyint, TaskSequence int, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_req_ilbo_local_info (ilbocode varchar(60) collate SQL_Latin1_General_CP1_CI_AS, Langid tinyint, Description varchar(255) collate SQL_Latin1_General_CP1_CI_AS, HelpIndex int, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_req_ilbo_tabs (ILBOCode varchar(60) collate SQL_Latin1_General_CP1_CI_AS, TabName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, BTSynonym varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_req_lang_bterm_synonym (BTSynonym varchar(60) collate SQL_Latin1_General_CP1_CI_AS, Langid tinyint, ForeignName varchar(120) collate SQL_Latin1_General_CP1_CI_AS, LongPLText nvarchar(240) collate SQL_Latin1_General_CP1_CI_AS, ShortPLText nvarchar(200) collate SQL_Latin1_General_CP1_CI_AS, ShortDesc nvarchar(510) collate SQL_Latin1_General_CP1_CI_AS, LongDesc varchar(510) collate SQL_Latin1_General_CP1_CI_AS, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_req_precision (PrecisionType varchar(60) collate SQL_Latin1_General_CP1_CI_AS, TotalLength int, DecimalLength int, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_req_ilbo_control_property  (controlid varchar(60) collate SQL_Latin1_General_CP1_CI_AS,ilbocode varchar(255) collate SQL_Latin1_General_CP1_CI_AS, propertyname varchar(60) collate SQL_Latin1_General_CP1_CI_AS,type varchar(60) collate SQL_Latin1_General_CP1_CI_AS, value varchar(255) collate SQL_Latin1_General_CP1_CI_AS,viewname varchar(60) collate SQL_Latin1_General_CP1_CI_AS , UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_req_ilbo_control (controlid varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ilbocode varchar(255) collate SQL_Latin1_General_CP1_CI_AS,tabname varchar(60) collate SQL_Latin1_General_CP1_CI_AS,type varchar(60) collate SQL_Latin1_General_CP1_CI_AS, listedit varchar(5) collate SQL_Latin1_General_CP1_CI_AS, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_req_ilbo_layout_control (ilbocode varchar(255) collate SQL_Latin1_General_CP1_CI_AS, tabname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, controlid varchar(60) collate SQL_Latin1_General_CP1_CI_AS, type varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
create table #fw_req_ilbo_view (btsynonym varchar(60) collate SQL_Latin1_General_CP1_CI_AS,controlid  varchar(60) collate SQL_Latin1_General_CP1_CI_AS,displayflag varchar(5) collate SQL_Latin1_General_CP1_CI_AS, displaylength int,ilbocode varchar(200) collate SQL_Latin1_General_CP1_CI_AS, viewname varchar(60) collate SQL_Latin1_General_CP1_CI_AS , UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime,  le_pop varchar(5) collate SQL_Latin1_General_CP1_CI_AS, seq_no int, isItkCtrl char(1) collate SQL_Latin1_General_CP1_CI_AS)
create table #fw_req_ilbo_task_control (btsynonym varchar(60) collate SQL_Latin1_General_CP1_CI_AS,activityid varchar(60)  collate SQL_Latin1_General_CP1_CI_AS,ilbocode varchar(60)  collate SQL_Latin1_General_CP1_CI_AS, taskname  varchar(100) collate SQL_Latin1_General_CP1_CI_AS,tasktype  varchar(20) collate SQL_Latin1_General_CP1_CI_AS )
create table #fw_req_bterm(btdesc varchar(250) collate SQL_Latin1_General_CP1_CI_AS,btname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, datatype varchar(20) collate SQL_Latin1_General_CP1_CI_AS,isbterm    int,length int, maxvalue  varchar(250) collate SQL_Latin1_General_CP1_CI_AS,minvalue   varchar(250) collate SQL_Latin1_General_CP1_CI_AS,precisiontype varchar(20) collate SQL_Latin1_General_CP1_CI_AS , UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_req_bterm_synonym(btname varchar(60) collate SQL_Latin1_General_CP1_CI_AS,btsynonym varchar(60) collate SQL_Latin1_General_CP1_CI_AS , UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_req_process_component(componentdesc varchar(255) collate SQL_Latin1_General_CP1_CI_AS,parentprocess varchar(255) collate SQL_Latin1_General_CP1_CI_AS, componentname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, sequenceno int , UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_req_ilbo_tab_properties(ilbocode varchar(200) collate SQL_Latin1_General_CP1_CI_AS, propertyname  varchar(64) collate SQL_Latin1_General_CP1_CI_AS,tabname varchar(60) collate SQL_Latin1_General_CP1_CI_AS,value  varchar(250) collate SQL_Latin1_General_CP1_CI_AS , UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime) 
create table #fw_req_activity_ilbo_task(activityid int, datasavingtask varchar(100) collate SQL_Latin1_General_CP1_CI_AS, ilbocode varchar(200) collate SQL_Latin1_General_CP1_CI_AS, linktype  int, taskname varchar(100) collate SQL_Latin1_General_CP1_CI_AS, activityname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, Taskconfirmation   int , usageid varchar(60) collate SQL_Latin1_General_CP1_CI_AS,ddt_control_id varchar(60) collate SQL_Latin1_General_CP1_CI_AS,ddt_view_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime, Tasktype varchar(60) collate SQL_Latin1_General_CP1_CI_AS) 
create table #fw_req_task(taskdesc varchar(250)  collate SQL_Latin1_General_CP1_CI_AS,taskname  varchar(100) collate SQL_Latin1_General_CP1_CI_AS,tasktype  varchar(20) collate SQL_Latin1_General_CP1_CI_AS , UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_req_bterm_enumerated_option(btname   varchar(60) collate SQL_Latin1_General_CP1_CI_AS,langid int, optioncode  varchar(8) collate SQL_Latin1_General_CP1_CI_AS, optiondesc  nvarchar(160) collate SQL_Latin1_General_CP1_CI_AS, sequenceno int, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_req_ilbo_link_publish(activityid int,description varchar(512) collate SQL_Latin1_General_CP1_CI_AS, ilbocode varchar(200) collate SQL_Latin1_General_CP1_CI_AS, linkid int, taskname varchar(100) collate SQL_Latin1_General_CP1_CI_AS , UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_req_ilbo_data_publish(controlid varchar(60) collate SQL_Latin1_General_CP1_CI_AS, controlvariablename varchar(60) collate SQL_Latin1_General_CP1_CI_AS, dataitemname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, flowtype int, havemultiple int, ilbocode  varchar(200) collate SQL_Latin1_General_CP1_CI_AS,iscontrol int, linkid  int, mandatoryflag  int, viewname   varchar(60) collate SQL_Latin1_General_CP1_CI_AS , UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_req_ilbo_data_use(childilbocode varchar(200) collate SQL_Latin1_General_CP1_CI_AS, controlid  varchar(60) collate SQL_Latin1_General_CP1_CI_AS, controlvariablename varchar(60) collate SQL_Latin1_General_CP1_CI_AS, dataitemname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, flowtype int, iscontrol int, linkid  int, parentilbocode  varchar(200) collate SQL_Latin1_General_CP1_CI_AS, primarydata  varchar(5) collate SQL_Latin1_General_CP1_CI_AS, retrievemultiple int, taskname varchar(100) collate SQL_Latin1_General_CP1_CI_AS, viewname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_req_ilbo_linkuse (childilbocode  varchar(200) collate SQL_Latin1_General_CP1_CI_AS, childorder int, linkid int, parentilbocode  varchar(200) collate SQL_Latin1_General_CP1_CI_AS, taskname  varchar(100) collate SQL_Latin1_General_CP1_CI_AS, posttask varchar(255) collate SQL_Latin1_General_CP1_CI_AS, post_linktask varchar(255) collate SQL_Latin1_General_CP1_CI_AS, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_des_ilbo_services (ilbocode  varchar(200) collate SQL_Latin1_General_CP1_CI_AS, isprepopulate tinyint, servicename    varchar(64) collate SQL_Latin1_General_CP1_CI_AS , UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime, IsUniversalPersonalization  varchar(5) collate SQL_Latin1_General_CP1_CI_AS) 
create table #fw_asp_codegen_tmp(ilbocode varchar(60) collate SQL_Latin1_General_CP1_CI_AS, IdentityId    varchar(120) collate SQL_Latin1_General_CP1_CI_AS,   SerialNo int, Position varchar(120) collate SQL_Latin1_General_CP1_CI_AS, ControlID  varchar(64) collate SQL_Latin1_General_CP1_CI_AS, Type varchar(120) collate SQL_Latin1_General_CP1_CI_AS, LineNum    int, AttributeName varchar(120) collate SQL_Latin1_General_CP1_CI_AS, InitVal varchar(120) collate SQL_Latin1_General_CP1_CI_AS, Script varchar(4000) collate SQL_Latin1_General_CP1_CI_AS )
create table #fw_req_system_parameters (paramname varchar(30) collate SQL_Latin1_General_CP1_CI_AS, paramvalue varchar(80) collate SQL_Latin1_General_CP1_CI_AS,  timestamp int, createdby varchar(60) collate SQL_Latin1_General_CP1_CI_AS, createddate datetime, modifiedby varchar(60) collate SQL_Latin1_General_CP1_CI_AS, modifieddate datetime, paramdesc varchar(255) collate SQL_Latin1_General_CP1_CI_AS)
create table #fw_des_service_dataitem(dataitemname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, defaultvalue varchar(60) collate SQL_Latin1_General_CP1_CI_AS, flowattribute int,ispartofkey int,mandatoryflag int, segmentname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, servicename varchar(60) collate SQL_Latin1_General_CP1_CI_AS, itk_dataitem varchar(2) collate SQL_Latin1_General_CP1_CI_AS, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS,  UpdTime datetime, controlid varchar(40)collate SQL_Latin1_General_CP1_CI_AS )
create table #fw_des_be_placeholder(errorid int  ,methodid int  ,parametername varchar(60) collate SQL_Latin1_General_CP1_CI_AS ,placeholdername varchar(60) collate SQL_Latin1_General_CP1_CI_AS ) 
create table #fw_des_br_logical_parameter ( methodid int  ,logicalparametername varchar(60) collate SQL_Latin1_General_CP1_CI_AS ,logicalparamseqno int,recordsetname varchar(60) collate SQL_Latin1_General_CP1_CI_AS ,rssequenceno smallint,flowdirection smallint, btname varchar(60) collate SQL_Latin1_General_CP1_CI_AS ,spparametertype varchar(20) collate SQL_Latin1_General_CP1_CI_AS, controlid varchar(40)collate SQL_Latin1_General_CP1_CI_AS )
create table #fw_des_brerror (errorid int  ,methodid int  ,sperrorcode varchar(12) collate SQL_Latin1_General_CP1_CI_AS)
create table #fw_des_bro (broname varchar(100) collate SQL_Latin1_General_CP1_CI_AS  , brodescription varchar(256) collate SQL_Latin1_General_CP1_CI_AS , componentname varchar(60) collate SQL_Latin1_General_CP1_CI_AS  ,broscope tinyint, brotype tinyint, clsid varchar(40) collate SQL_Latin1_General_CP1_CI_AS ,clsname varchar(40) collate SQL_Latin1_General_CP1_CI_AS ,dllname varchar(510) collate SQL_Latin1_General_CP1_CI_AS,progid varchar(510) collate SQL_Latin1_General_CP1_CI_AS ,systemgenerated tinyint)
create table #fw_des_businessrule(accessesdatabase tinyint,bocode varchar(100) collate SQL_Latin1_General_CP1_CI_AS , broname varchar(100) collate SQL_Latin1_General_CP1_CI_AS , dispid varchar(510) collate SQL_Latin1_General_CP1_CI_AS ,isintegbr tinyint, methodid int  , methodname varchar(510) collate SQL_Latin1_General_CP1_CI_AS , operationtype tinyint,statusflag tinyint,systemgenerated tinyint,method_exec_cont varchar(5)) 
create table #fw_des_context(correctiveaction varchar(4000) collate SQL_Latin1_General_CP1_CI_AS,errorcontext varchar(510) collate SQL_Latin1_General_CP1_CI_AS ,errorid int  ,severityid tinyint)
create table #fw_des_di_parameter
(
                dataitemname varchar(60) collate SQL_Latin1_General_CP1_CI_AS ,
                methodid int  , 
                parametername varchar(60) collate SQL_Latin1_General_CP1_CI_AS , 
                sectionname varchar(60) collate SQL_Latin1_General_CP1_CI_AS , 
                segmentname varchar(60) collate SQL_Latin1_General_CP1_CI_AS , 
                sequenceno int ,
                servicename varchar(64) collate SQL_Latin1_General_CP1_CI_AS, old_seq_no int, 
                old_seq_no_ins int, 
                le_pop varchar(5) collate SQL_Latin1_General_CP1_CI_AS 
) 
create table #fw_des_di_placeholder(dataitemname varchar(60) collate SQL_Latin1_General_CP1_CI_AS ,errorid  int  , methodid int  , placeholdername varchar(60) collate SQL_Latin1_General_CP1_CI_AS , sectionname varchar(60) collate SQL_Latin1_General_CP1_CI_AS , segmentname varchar(60) collate SQL_Latin1_General_CP1_CI_AS , sequenceno int ,servicename varchar(64)  collate SQL_Latin1_General_CP1_CI_AS, old_seq_no int, old_seq_no_ins int) 
create table #fw_des_error (componentname varchar(60) collate SQL_Latin1_General_CP1_CI_AS  ,defaultcorrectiveaction varchar(4000) collate SQL_Latin1_General_CP1_CI_AS,defaultseverity tinyint, detaileddesc varchar(2000) collate SQL_Latin1_General_CP1_CI_AS , displaytype varchar(30) collate SQL_Latin1_General_CP1_CI_AS,errorid  int  , errormessage nvarchar(1020) collate SQL_Latin1_General_CP1_CI_AS , errorsource tinyint,reqerror varchar(40) collate SQL_Latin1_General_CP1_CI_AS)
create table #fw_des_integ_serv_map (callingdataitem varchar(60) collate SQL_Latin1_General_CP1_CI_AS , callingsegment varchar(60) collate SQL_Latin1_General_CP1_CI_AS , callingservicename varchar(64) collate SQL_Latin1_General_CP1_CI_AS  , integdataitem varchar(60) collate SQL_Latin1_General_CP1_CI_AS , integsegment varchar(60) collate SQL_Latin1_General_CP1_CI_AS  , integservicename varchar(64) collate SQL_Latin1_General_CP1_CI_AS  , sectionname varchar(60) collate SQL_Latin1_General_CP1_CI_AS  , sequenceno int, old_seq_no int, old_seq_no_ins int)
create table #fw_des_processsection( controlexpression varchar(256) collate SQL_Latin1_General_CP1_CI_AS,processingtype tinyint,sectionname varchar(60) collate SQL_Latin1_General_CP1_CI_AS , sectiontype tinyint , sequenceno int , servicename varchar(64) collate SQL_Latin1_General_CP1_CI_AS, old_seq_no int, old_seq_no_ins int, IsUniversalPersonalization varchar(5) collate SQL_Latin1_General_CP1_CI_AS, IsUniversalPersonlizedSection varchar(5) collate SQL_Latin1_General_CP1_CI_AS)
 
--create table #fw_des_processsection_br_is (connectivityflag tinyint, controlexpression varchar(256) collate SQL_Latin1_General_CP1_CI_AS,executionflag tinyint, integservicename varchar(64) collate SQL_Latin1_General_CP1_CI_AS , isbr tinyint, methodid int  , sectionname varchar(60) collate SQL_Latin1_General_CP1_CI_AS , sequenceno int , servicename varchar(64) collate SQL_Latin1_General_CP1_CI_AS, old_seq_no int, old_seq_no_ins int, Method_Ext char(2), methodid_ref int, methodname_ref varchar(64) collate SQL_Latin1_General_CP1_CI_AS, sequenceno_ref int, sectionname_ref varchar(64) collate SQL_Latin1_General_CP1_CI_AS, ps_sequenceno_ref int,loopcausingsegment varchar(60) collate SQL_Latin1_General_CP1_CI_AS )
create table #fw_des_processsection_br_is (connectivityflag tinyint, controlexpression varchar(256) collate SQL_Latin1_General_CP1_CI_AS,executionflag tinyint, integservicename varchar(64) collate SQL_Latin1_General_CP1_CI_AS , isbr tinyint, methodid int  , sectionname varchar(60) collate SQL_Latin1_General_CP1_CI_AS , sequenceno int , servicename varchar(64) collate SQL_Latin1_General_CP1_CI_AS, old_seq_no int, old_seq_no_ins int, Method_Ext char(2), methodid_ref int, methodname_ref varchar(64) collate SQL_Latin1_General_CP1_CI_AS, sequenceno_ref int, sectionname_ref varchar(64) collate SQL_Latin1_General_CP1_CI_AS, ps_sequenceno_ref int,loopcausingsegment varchar(60) collate SQL_Latin1_General_CP1_CI_AS,SpecID int,SpecName varchar(300),SpecVersion int,Path varchar(500),OperationID varchar(100),OperationVerb varchar(10), IsUniversalPersonlizedSection varchar(5) collate SQL_Latin1_General_CP1_CI_AS,UPEControlExpr varchar(2) collate SQL_Latin1_General_CP1_CI_AS )
 
create table #fw_des_processsection_br_is_err (connectivityflag tinyint, controlexpression varchar(256) collate SQL_Latin1_General_CP1_CI_AS,executionflag tinyint, integservicename varchar(64) collate SQL_Latin1_General_CP1_CI_AS , isbr tinyint, methodid int, sectionname varchar(60) collate SQL_Latin1_General_CP1_CI_AS not null, sequenceno int not null, servicename varchar(64) collate SQL_Latin1_General_CP1_CI_AS not null)
create table #fw_des_sp (methodid int  ,sperrorprotocol tinyint, spname varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
create table #fw_des_bo ( BOCode varchar(64) collate SQL_Latin1_General_CP1_CI_AS  , ComponentName varchar(64) collate SQL_Latin1_General_CP1_CI_AS , BODesc varchar(255) collate SQL_Latin1_General_CP1_CI_AS , StatusFlag int ) 
create table #fw_des_svco( SVCOName varchar(60) collate SQL_Latin1_General_CP1_CI_AS , SVCODescription varchar(255) collate SQL_Latin1_General_CP1_CI_AS , ComponentName varchar(60) collate SQL_Latin1_General_CP1_CI_AS , SVCOScope int ,SVCOType int ,DLLName varchar(60) collate SQL_Latin1_General_CP1_CI_AS ,ProgID varchar(255) collate SQL_Latin1_General_CP1_CI_AS ) 
create table #fw_des_error_placeholder (ErrorID int, PlaceholderName varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
create table #fw_des_reqbr_desbr ( ReqBRName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, MethodID int )
create table #fw_req_task_rule (TaskName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, BRSequence int, BRName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, InvocationType tinyint) 
create table #fw_des_ilbo_placeholder (ilbocode varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ControlID varchar(64) collate SQL_Latin1_General_CP1_CI_AS, EventName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, PlaceholderName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, IsControl tinyint, ControlName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ViewName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, VariableName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ErrorID varchar(40) collate SQL_Latin1_General_CP1_CI_AS, CtrlEvent_ViewName varchar(60) collate SQL_Latin1_General_CP1_CI_AS) 
create table #fw_des_ilbo_ctrl_event  (ILBOCode varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ControlID varchar(60) collate SQL_Latin1_General_CP1_CI_AS, EventName varchar(60) collate SQL_Latin1_General_CP1_CI_AS,  TaskName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, MethodName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, CreateStubFlag tinyint, ViewName varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
create table #fw_req_businessrule (BRName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, BRType varchar(20) collate SQL_Latin1_General_CP1_CI_AS, BRDesc varchar(510) collate SQL_Latin1_General_CP1_CI_AS) 
create table #fw_req_br_error ( BRName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ErrorCode varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
CREATE TABLE #fw_req_ILBO_Transpose ( ComponentName varchar(60) collate SQL_Latin1_General_CP1_CI_AS NOT NULL, ActivityName varchar(60) collate SQL_Latin1_General_CP1_CI_AS NOT NULL, [ILBOCode] varchar(200) collate SQL_Latin1_General_CP1_CI_AS NOT NULL, [ControlID] varchar(64) collate SQL_Latin1_General_CP1_CI_AS NOT NULL, [ZoomName] varchar(13) collate SQL_Latin1_General_CP1_CI_AS NOT NULL, [Version] varchar(7) collate SQL_Latin1_General_CP1_CI_AS NOT NULL ,UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_req_ilbo_task_rpt ( ilbocode varchar(60) collate SQL_Latin1_General_CP1_CI_AS,taskname varchar(60) collate SQL_Latin1_General_CP1_CI_AS,PageName varchar(60) collate SQL_Latin1_General_CP1_CI_AS,ProcessingType varchar(60) collate SQL_Latin1_General_CP1_CI_AS,ContextName varchar(4000) collate SQL_Latin1_General_CP1_CI_AS, ReportType varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
Create table #fw_des_chart_service_segment (component_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, chart_id varchar(60) collate SQL_Latin1_General_CP1_CI_AS, chart_section varchar(60) collate SQL_Latin1_General_CP1_CI_AS, servicename varchar(60) collate SQL_Latin1_General_CP1_CI_AS, segmentname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, instanceflag int) 
Create table #fw_task_service_map (activity_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS ,service_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, task_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS,ui_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS )
create table #fw_des_service ( isintegser tinyint, processingtype tinyint, servicename varchar(60) collate SQL_Latin1_General_CP1_CI_AS, servicetype int,statusflag int, svconame varchar(60) collate SQL_Latin1_General_CP1_CI_AS, componentname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, isCached varchar(5) collate SQL_Latin1_General_CP1_CI_AS, isZipped varchar(5) collate SQL_Latin1_General_CP1_CI_AS, SetKey_Pattern varchar(255) collate SQL_Latin1_General_CP1_CI_AS, ClearKey_Pattern varchar(255) collate SQL_Latin1_General_CP1_CI_AS, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_des_service_segment (bocode varchar(60) collate SQL_Latin1_General_CP1_CI_AS, bosegmentname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, instanceflag int, mandatoryflag int, parentsegmentname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, segmentname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, servicename varchar(60) collate SQL_Latin1_General_CP1_CI_AS, SegmentSequence int, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime, process_selrows varchar(2) collate SQL_Latin1_General_CP1_CI_AS, process_updrows varchar(2) collate SQL_Latin1_General_CP1_CI_AS,process_selupdrows varchar(2) collate SQL_Latin1_General_CP1_CI_AS,flowattribute int,UPEComboFilling varchar(2) collate SQL_Latin1_General_CP1_CI_AS, persistscrollposition varchar(5) collate SQL_Latin1_General_CP1_CI_AS, atomicrefresh varchar(5) collate SQL_Latin1_General_CP1_CI_AS)
create table #fw_des_ilbo_service_view_datamap (activityid    int, controlid  varchar(60) collate SQL_Latin1_General_CP1_CI_AS, dataitemname   varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ilbocode  varchar(200) collate SQL_Latin1_General_CP1_CI_AS, iscontrol tinyint, segmentname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, servicename varchar(64) collate SQL_Latin1_General_CP1_CI_AS, taskname varchar(100) collate SQL_Latin1_General_CP1_CI_AS, variablename varchar(60) collate SQL_Latin1_General_CP1_CI_AS, viewname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, page_bt_synonym varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime)
create table #fw_des_task_segment_attribs (activityid int, ilbocode varchar(200) collate SQL_Latin1_General_CP1_CI_AS, taskname  varchar(100) collate SQL_Latin1_General_CP1_CI_AS,servicename  varchar(64) collate SQL_Latin1_General_CP1_CI_AS, segmentname  varchar(60) collate SQL_Latin1_General_CP1_CI_AS,combofill  int, displayflag varchar(5) collate SQL_Latin1_General_CP1_CI_AS, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime) 
create table #fw_req_task_local_info (langid tinyint, taskname  varchar(100) collate SQL_Latin1_General_CP1_CI_AS, description  varchar(512) collate SQL_Latin1_General_CP1_CI_AS, helpindex int, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime) 
create table #fw_req_ilbo_link_local_info (LinkID int, ilbocode varchar(60) collate SQL_Latin1_General_CP1_CI_AS, Langid tinyint, Description varchar(255) collate SQL_Latin1_General_CP1_CI_AS, HelpIndex int, UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime) 
create table #fw_req_activity_ilbo_task_extension_map (componentname  varchar(60) collate SQL_Latin1_General_CP1_CI_AS, activityid int, ilbocode varchar(60) collate SQL_Latin1_General_CP1_CI_AS, taskname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, resultantaspname varchar(512) collate SQL_Latin1_General_CP1_CI_AS, sessionvariable varchar(60) collate SQL_Latin1_General_CP1_CI_AS , UpdUser varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime) 
create table #LP_RVWObjects_tmp(ObjectType NVARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS, ObjectCode NVARCHAR(200) collate SQL_Latin1_General_CP1_CI_AS )
create table #LP_ILBO_Tmp(ILBOCode NVARCHAR(300) collate SQL_Latin1_General_CP1_CI_AS,processFlag  NVARCHAR(300) collate SQL_Latin1_General_CP1_CI_AS, publishflag  NVARCHAR(300) collate SQL_Latin1_General_CP1_CI_AS)
create table #LP_Service_Tmp( ServiceName NVARCHAR(100) collate SQL_Latin1_General_CP1_CI_AS, ServiceLevel INT, ServiceFlag INT)
create table #service_tmp (ServiceName  NVARCHAR(100) collate SQL_Latin1_General_CP1_CI_AS, processflag NVARCHAR(100) collate SQL_Latin1_General_CP1_CI_AS, publishflag NVARCHAR(100) collate SQL_Latin1_General_CP1_CI_AS)
create table #LP_PublishErr_Tmp( ObjectType NVARCHAR(100) collate SQL_Latin1_General_CP1_CI_AS,  ObjectCode NVARCHAR(200) collate SQL_Latin1_General_CP1_CI_AS, ErrorID INT)
create table #fw_des_focus_control (ErrorID int, ErrorContext varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ControlID varchar(60) collate SQL_Latin1_General_CP1_CI_AS , SegmentName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, FocusDataItem varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UpdUser varchar(60)  collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime, methodid int, method_name varchar(510) collate SQL_Latin1_General_CP1_CI_AS)
create table #meta_severity (SeverityID tinyint, SeverityDesc varchar(255) collate SQL_Latin1_General_CP1_CI_AS, DefButton varchar(100) collate SQL_Latin1_General_CP1_CI_AS, ErrorSource varchar(120) collate SQL_Latin1_General_CP1_CI_AS, ButtonText varchar(100) collate SQL_Latin1_General_CP1_CI_AS) 
create table #fw_req_activity_PLBO(ActivityId varchar(100) collate SQL_Latin1_General_CP1_CI_AS,PLBOCode varchar(100) collate SQL_Latin1_General_CP1_CI_AS) 
create table #fw_req_plbo (PLBOCode varchar(100) collate SQL_Latin1_General_CP1_CI_AS, Description varchar(510) collate SQL_Latin1_General_CP1_CI_AS, PLBOType tinyint, ProgID varchar(256) collate SQL_Latin1_General_CP1_CI_AS, StatusFlag tinyint) 
create table #fw_des_ilbo_focus_control (ErrorID int, ErrorContext varchar(510) collate SQL_Latin1_General_CP1_CI_AS, ControlID varchar(60) collate SQL_Latin1_General_CP1_CI_AS, SegmentName varchar(60) collate SQL_Latin1_General_CP1_CI_AS,  FocusDataItem varchar(60) collate SQL_Latin1_General_CP1_CI_AS) 
create table #fw_des_service_view_datamap (PLBOCode varchar(100) collate SQL_Latin1_General_CP1_CI_AS, ServiceName varchar(64) collate SQL_Latin1_General_CP1_CI_AS, TaskName varchar(100) collate SQL_Latin1_General_CP1_CI_AS, SegmentName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, DataItemName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, IsControl tinyint, ControlID varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ViewName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, VariableName varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
create table #fw_des_ilerror (ILBOCode varchar(100) collate SQL_Latin1_General_CP1_CI_AS, ControlID varchar(60) collate SQL_Latin1_General_CP1_CI_AS, EventName varchar(100) collate SQL_Latin1_General_CP1_CI_AS, LocalErrorNo int, ErrorID int, ViewName varchar(60) collate SQL_Latin1_General_CP1_CI_AS) 
create table #fw_des_err_det_local_info (ErrorID int, ErrorMessage nvarchar(1020) collate SQL_Latin1_General_CP1_CI_AS, DetailedDesc varchar(4000) collate SQL_Latin1_General_CP1_CI_AS, LangId tinyint)
create table #fw_des_corr_action_local_info (ErrorID varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ErrorContext varchar(510) collate SQL_Latin1_General_CP1_CI_AS, CorrectiveAction varchar(4000) collate SQL_Latin1_General_CP1_CI_AS, LangId tinyint) 
create table #es_comp_ctrl_type_mst(customer_name varchar(60) collate sql_latin1_general_cp1_ci_as,project_name varchar(60) collate sql_latin1_general_cp1_ci_as,req_no varchar(60) collate sql_latin1_general_cp1_ci_as,process_name varchar(60) collate sql_latin1_general_cp1_ci_as,component_name varchar(60) collate sql_latin1_general_cp1_ci_as,ctrl_type_name varchar(60) collate sql_latin1_general_cp1_ci_as,ctrl_type_descr varchar(255) collate sql_latin1_general_cp1_ci_as,base_ctrl_type varchar(60) collate sql_latin1_general_cp1_ci_as, mandatory_flag varchar(5) collate sql_latin1_general_cp1_ci_as,visisble_flag varchar(5) collate sql_latin1_general_cp1_ci_as,editable_flag varchar(5) collate sql_latin1_general_cp1_ci_as,caption_req varchar(5) collate sql_latin1_general_cp1_ci_as,select_flag  varchar(5) collate sql_latin1_general_cp1_ci_as,zoom_req varchar(5) collate sql_latin1_general_cp1_ci_as,insert_req varchar(5) collate sql_latin1_general_cp1_ci_as,delete_req varchar(5) collate sql_latin1_general_cp1_ci_as,help_req varchar(5) collate sql_latin1_general_cp1_ci_as, event_handling_req  varchar(5) collate sql_latin1_general_cp1_ci_as,ellipses_req varchar(5) collate sql_latin1_general_cp1_ci_as,comp_ctrl_type_sysid varchar(40) collate sql_latin1_general_cp1_ci_as,timestamp int,createdby varchar(30) collate sql_latin1_general_cp1_ci_as,createddate datetime,modifiedby varchar(30) collate sql_latin1_general_cp1_ci_as,modifieddate datetime,visisble_rows varchar(5) collate sql_latin1_general_cp1_ci_as,ctrl_type_doc varchar(4000) collate sql_latin1_general_cp1_ci_as,caption_alignment varchar(8) collate sql_latin1_general_cp1_ci_as, caption_wrap varchar(5) collate sql_latin1_general_cp1_ci_as,caption_position varchar(8) collate sql_latin1_general_cp1_ci_as,ctrl_position varchar(8) collate sql_latin1_general_cp1_ci_as,label_class varchar(60) collate sql_latin1_general_cp1_ci_as,ctrl_class varchar(60) collate sql_latin1_general_cp1_ci_as,password_char varchar(5) collate sql_latin1_general_cp1_ci_as,tskimg_class varchar(60) collate sql_latin1_general_cp1_ci_as,hlpimg_class varchar(60) collate sql_latin1_general_cp1_ci_as,disponlycmb_req varchar(5) collate sql_latin1_general_cp1_ci_as, html_txt_area varchar(5) collate sql_latin1_general_cp1_ci_as, report_req varchar(5) collate sql_latin1_general_cp1_ci_as,auto_tab_stop varchar(5) collate sql_latin1_general_cp1_ci_as,spin_required varchar(5) collate sql_latin1_general_cp1_ci_as,spin_up_image varchar(60) collate sql_latin1_general_cp1_ci_as,spin_down_image varchar(60) collate sql_latin1_general_cp1_ci_as, Extjs_Ctrl_type varchar(60) collate sql_latin1_general_cp1_ci_as)
Create Table #fw_req_language (customername  varchar(60) collate SQL_Latin1_General_CP1_CI_AS, projectname  varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ecrno  varchar(60) collate SQL_Latin1_General_CP1_CI_AS, langid int, langdesc varchar(225) collate SQL_Latin1_General_CP1_CI_AS)
create table #fw_des_plbo_placeholder (PLBOCode varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ControlID varchar(60) collate SQL_Latin1_General_CP1_CI_AS, EventName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, PlaceholderName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ControlName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ViewName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ErrorID int, CtrlEvent_ViewName varchar(60) collate SQL_Latin1_General_CP1_CI_AS) 
create table #fw_req_control_property (PLBOCode varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ControlID varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ViewName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, PropertyName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, Type varchar(20) collate SQL_Latin1_General_CP1_CI_AS, Value varchar(510) collate SQL_Latin1_General_CP1_CI_AS) 
create table #fw_des_plerror (PLBOCode varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ControlID varchar(60) collate SQL_Latin1_General_CP1_CI_AS, EventName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, LocalErrorNo int, ErrorID int , ViewName varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
create table #fw_req_activity_local_info ( activityid int ,langid int ,activitydesc varchar(255) collate SQL_Latin1_General_CP1_CI_AS ,helpindex int ,tooltiptext varchar(255) collate SQL_Latin1_General_CP1_CI_AS)
create table #fw_req_ilboctrl_initval (ilbocode varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ControlID varchar(64) collate SQL_Latin1_General_CP1_CI_AS, ViewName varchar(60) collate SQL_Latin1_General_CP1_CI_AS , sequenceNo int, InitialValue varchar(510) collate SQL_Latin1_General_CP1_CI_AS, UpdUser varchar(64) collate SQL_Latin1_General_CP1_CI_AS, UpdTime datetime) 
create table #fw_service_validation_message (service_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, languageid int, segmentname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, dataitemname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, validation_code varchar(60) collate SQL_Latin1_General_CP1_CI_AS, message_code int, message_doc varchar(255) collate SQL_Latin1_General_CP1_CI_AS, value1 varchar(255) collate SQL_Latin1_General_CP1_CI_AS, value2 varchar(255) collate SQL_Latin1_General_CP1_CI_AS, order_of_sequence int)
create table #de_published_ui_control(component_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS,activity_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS,control_bt_synonym varchar(60) collate SQL_Latin1_General_CP1_CI_AS,control_doc varchar(400) collate SQL_Latin1_General_CP1_CI_AS,control_id varchar(60) collate SQL_Latin1_General_CP1_CI_AS,control_prefix varchar(6) collate SQL_Latin1_General_CP1_CI_AS,control_type varchar(60) collate SQL_Latin1_General_CP1_CI_AS,data_column_width int,horder int,label_column_width int,order_seq int,page_bt_synonym varchar(60) collate SQL_Latin1_General_CP1_CI_AS,proto_tooltip varchar(255) collate SQL_Latin1_General_CP1_CI_AS,sample_data varchar(4000) collate SQL_Latin1_General_CP1_CI_AS,section_bt_synonym varchar(60) collate SQL_Latin1_General_CP1_CI_AS,timestamp int,ui_control_sysid varchar(40) collate SQL_Latin1_General_CP1_CI_AS,ui_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS,ui_section_sysid varchar(40) collate SQL_Latin1_General_CP1_CI_AS,view_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS,visisble_length numeric(5),vorder int,label_column_scalemode varchar(6) collate SQL_Latin1_General_CP1_CI_AS,data_column_scalemode varchar(6) collate SQL_Latin1_General_CP1_CI_AS,tab_seq int,help_tabstop varchar(5) collate SQL_Latin1_General_CP1_CI_AS,LabelClass varchar(60) collate SQL_Latin1_General_CP1_CI_AS,ControlClass varchar(60) collate SQL_Latin1_General_CP1_CI_AS,LabelImageClass varchar(60) collate SQL_Latin1_General_CP1_CI_AS,ControlImageClass varchar(60) collate SQL_Latin1_General_CP1_CI_AS,label_control_id varchar(60) collate SQL_Latin1_General_CP1_CI_AS,req_no varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
create table #de_published_ui_grid(activity_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, column_bt_synonym varchar(60) collate SQL_Latin1_General_CP1_CI_AS, column_no int, column_prefix varchar(6) collate SQL_Latin1_General_CP1_CI_AS, column_type varchar(60) collate SQL_Latin1_General_CP1_CI_AS, col_doc varchar(4000) collate SQL_Latin1_General_CP1_CI_AS, component_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, control_bt_synonym varchar(60) collate SQL_Latin1_General_CP1_CI_AS, control_id varchar(60) collate SQL_Latin1_General_CP1_CI_AS, grid_sysid varchar(40) collate SQL_Latin1_General_CP1_CI_AS, page_bt_synonym varchar(60) collate SQL_Latin1_General_CP1_CI_AS, proto_tooltip varchar(255) collate SQL_Latin1_General_CP1_CI_AS, sample_data varchar(4000) collate SQL_Latin1_General_CP1_CI_AS, section_bt_synonym varchar(255) collate SQL_Latin1_General_CP1_CI_AS, timestamp int, ui_control_sysid varchar(40) collate SQL_Latin1_General_CP1_CI_AS, ui_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, view_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, visible_length numeric(5), req_no varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
create table #de_published_ui_page(activity_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, component_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, horder int, page_bt_synonym varchar(30) collate SQL_Latin1_General_CP1_CI_AS, page_doc varchar(4000) collate SQL_Latin1_General_CP1_CI_AS,  page_prefix varchar(6) collate SQL_Latin1_General_CP1_CI_AS, timestamp int, ui_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ui_page_sysid varchar(40) collate SQL_Latin1_General_CP1_CI_AS, ui_sysid varchar(40) collate SQL_Latin1_General_CP1_CI_AS, vorder int, req_no varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
create table #de_listedit_view_datamap(activity_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ilbocode varchar(60) collate SQL_Latin1_General_CP1_CI_AS, controlid varchar(60) collate SQL_Latin1_General_CP1_CI_AS, viewname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, listedit varchar(60) collate SQL_Latin1_General_CP1_CI_AS, instance int)
create table #de_ezeereport_task_control(component_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, activity_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ui_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, page_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, control_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, control_id varchar(60) collate SQL_Latin1_General_CP1_CI_AS, task_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS) 
create table #published_ui(activity_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, base_activity_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, base_component_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, base_ui_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, caption_alignment varchar(60) collate SQL_Latin1_General_CP1_CI_AS, current_req_no varchar(60) collate SQL_Latin1_General_CP1_CI_AS, tab_height int, trail_bar varchar(5) collate SQL_Latin1_General_CP1_CI_AS, ui_descr varchar(255) collate SQL_Latin1_General_CP1_CI_AS, ui_doc varchar(4000) collate SQL_Latin1_General_CP1_CI_AS, ui_format varchar(5) collate SQL_Latin1_General_CP1_CI_AS, ui_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ui_sysid varchar(40) collate SQL_Latin1_General_CP1_CI_AS, ui_type varchar(60) collate SQL_Latin1_General_CP1_CI_AS, grid_type varchar(20) collate SQL_Latin1_General_CP1_CI_AS, state_processing varchar(20) collate SQL_Latin1_General_CP1_CI_AS, req_no varchar(60) collate SQL_Latin1_General_CP1_CI_AS, callout_type varchar(20) collate SQL_Latin1_General_CP1_CI_AS, taskpane_req varchar(5) collate SQL_Latin1_General_CP1_CI_AS)
create table #fw_des_publish_ilbo_service_view_attributemap (activityid  int, controlid  varchar(60) collate SQL_Latin1_General_CP1_CI_AS, dataitemname   varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ilbocode  varchar(200) collate SQL_Latin1_General_CP1_CI_AS, segmentname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, servicename varchar(64) collate SQL_Latin1_General_CP1_CI_AS, taskname varchar(100) collate SQL_Latin1_General_CP1_CI_AS, viewname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, PropertyType varchar(60) collate SQL_Latin1_General_CP1_CI_AS, PropertyName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, Page_bt_Synonym varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
create table #fw_req_activity_ilbo_task_tabs(activityid int,  ilbocode varchar(200) collate SQL_Latin1_General_CP1_CI_AS, taskname varchar(100) collate SQL_Latin1_General_CP1_CI_AS, tabname varchar(60) collate SQL_Latin1_General_CP1_CI_AS) 
create table #fw_des_service_dtl(servicename varchar(60) collate sql_latin1_general_cp1_ci_as, servicetype int, insegs varchar(8000) collate sql_latin1_general_cp1_ci_as, outsegs varchar(8000) collate sql_latin1_general_cp1_ci_as, iosegs varchar(8000) collate sql_latin1_general_cp1_ci_as, scsegs varchar(8000) collate sql_latin1_general_cp1_ci_as, insegcnt int, outsegcnt int, scsegcnt int, pscnt int, iosegcnt int, datasegs varchar(8000) collate sql_latin1_general_cp1_ci_as, segcnt int, Junk_outscsegs varchar(200) collate sql_latin1_general_cp1_ci_as, junk_inscsegs int)
create table #fw_des_service_segment_dtl(servicename varchar(60) collate sql_latin1_general_cp1_ci_as, segmentname varchar(60) collate sql_latin1_general_cp1_ci_as, instanceflag int, parentsegment varchar(60) collate sql_latin1_general_cp1_ci_as, flowdirection int, mandatoryflag int, ispartofhierarchy int, isscratchdipartofsegment int, segmentsequence int, segkeys int, dicnt int, indinames  varchar(8000) collate sql_latin1_general_cp1_ci_as, iodinames varchar(8000) collate sql_latin1_general_cp1_ci_as, outdinames varchar(8000) collate sql_latin1_general_cp1_ci_as, scdinames varchar(8000) collate sql_latin1_general_cp1_ci_as, dinames varchar(8000) collate sql_latin1_general_cp1_ci_as, indicnt int, outdicnt int, iodicnt int, scdicnt int)
create table #fw_des_integ_outsegmap_dtl(servicename varchar(60) collate sql_latin1_general_cp1_ci_as, callerservice  varchar(60) collate sql_latin1_general_cp1_ci_as, sectionname varchar(60) collate sql_latin1_general_cp1_ci_as, sequenceno int, isCompName varchar(60) collate sql_latin1_general_cp1_ci_as, isSegList varchar(8000) collate sql_latin1_general_cp1_ci_as)
create table #fw_des_integ_segmap_dtl( callerservice varchar(60) collate sql_latin1_general_cp1_ci_as, integservice varchar(60) collate sql_latin1_general_cp1_ci_as, sectionname varchar(60) collate sql_latin1_general_cp1_ci_as, sequenceno int, callerSegList varchar(8000) collate sql_latin1_general_cp1_ci_as,isCompName varchar(60) collate sql_latin1_general_cp1_ci_as, callerOuSeg varchar(60) collate sql_latin1_general_cp1_ci_as, callerOuDi varchar(8000) collate sql_latin1_general_cp1_ci_as, isInSegList varchar(8000) collate sql_latin1_general_cp1_ci_as)
create table #fw_des_processsection_dtl(servicename varchar(60) collate sql_latin1_general_cp1_ci_as, sectionname varchar(60) collate sql_latin1_general_cp1_ci_as,sectiontype tinyint, seqNo tinyint, controlexpression varchar(256) collate sql_latin1_general_cp1_ci_as, loopingStyle tinyint, loopcausingsegment varchar(60) collate sql_latin1_general_cp1_ci_as,loopinstanceflag tinyint, ceInstDepFlag tinyint, brsCnt int)
create table #fw_des_service_dataitem_dtl (servicename varchar(60) collate sql_latin1_general_cp1_ci_as, segmentname varchar(60) collate sql_latin1_general_cp1_ci_as, dataitemname varchar(60) collate sql_latin1_general_cp1_ci_as, datatype varchar(20) collate sql_latin1_general_cp1_ci_as, datalength int, ispartofkey int, flowattribute int, mandatoryflag int, defaultvalue varchar(510) collate sql_latin1_general_cp1_ci_as, BT_Type varchar(20) collate sql_latin1_general_cp1_ci_as, isModel char(2) collate sql_latin1_general_cp1_ci_as )
create table #fw_des_parameter_cnt(servicename varchar(60) collate sql_latin1_general_cp1_ci_as, segmentname varchar(60) collate sql_latin1_general_cp1_ci_as, dataitemname varchar(60) collate sql_latin1_general_cp1_ci_as, br_totcnt int, br_incnt int)
create table #fw_ezeeview_sp(component_name varchar(60) collate sql_latin1_general_cp1_ci_as, activity_name varchar(60) collate sql_latin1_general_cp1_ci_as,ui_name varchar(60) collate sql_latin1_general_cp1_ci_as, taskname varchar(60) collate sql_latin1_general_cp1_ci_as, page_bt_synonym varchar(60) collate sql_latin1_general_cp1_ci_as, Link_ControlName varchar(60) collate sql_latin1_general_cp1_ci_as, Target_SPName varchar(60) collate sql_latin1_general_cp1_ci_as, Link_Caption varchar(60) collate sql_latin1_general_cp1_ci_as, Linked_Component varchar(60) collate sql_latin1_general_cp1_ci_as, Linked_Activity varchar(60) collate sql_latin1_general_cp1_ci_as, Linked_ui varchar(60) collate sql_latin1_general_cp1_ci_as) 
create table #fw_ezeeview_spparamlist(component_name varchar(60) collate sql_latin1_general_cp1_ci_as, activity_name varchar(60) collate sql_latin1_general_cp1_ci_as, ui_name varchar(60) collate sql_latin1_general_cp1_ci_as, page_bt_synonym varchar(60) collate sql_latin1_general_cp1_ci_as, Link_ControlName varchar(60) collate sql_latin1_general_cp1_ci_as, Target_SPName varchar(60) collate sql_latin1_general_cp1_ci_as, ParameterName varchar(60) collate sql_latin1_general_cp1_ci_as, Mapped_Control varchar(60) collate sql_latin1_general_cp1_ci_as, Link_Caption varchar(60) collate sql_latin1_general_cp1_ci_as, taskname varchar(60) collate sql_latin1_general_cp1_ci_as, controlid varchar(60) collate sql_latin1_general_cp1_ci_as, viewname varchar(60) collate sql_latin1_general_cp1_ci_as) 
create table #fw_des_caller_integ_serv_map (componentname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, callingservicename varchar(60) collate SQL_Latin1_General_CP1_CI_AS, callingsegment varchar(60) collate SQL_Latin1_General_CP1_CI_AS, callingdataitem varchar(60) collate SQL_Latin1_General_CP1_CI_AS, integservicename varchar(60) collate SQL_Latin1_General_CP1_CI_AS, integsegment varchar(60) collate SQL_Latin1_General_CP1_CI_AS, integdataitem varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
create table #fw_extjs_link_grid_map (taskname varchar(100) collate SQL_Latin1_General_CP1_CI_AS, ui_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, subscribed_control_id varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
create table #fw_extjs_control_dtl (activityname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, uiname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, taskname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, servicename varchar(60) collate SQL_Latin1_General_CP1_CI_AS, segmentname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, sectiontype varchar(60) collate SQL_Latin1_General_CP1_CI_AS, controlid varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
create table #de_published_action(activity_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, component_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, page_bt_synonym varchar(60) collate SQL_Latin1_General_CP1_CI_AS, primary_control_bts varchar(60) collate SQL_Latin1_General_CP1_CI_AS, task_descr varchar(255) collate SQL_Latin1_General_CP1_CI_AS, task_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, task_pattern varchar(60) collate SQL_Latin1_General_CP1_CI_AS, task_seq int, task_type varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ui_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, task_confirm_msg varchar(255) collate SQL_Latin1_General_CP1_CI_AS, task_status_msg varchar(255) collate SQL_Latin1_General_CP1_CI_AS, usageid varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ddt_page_bt_synonym varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ddt_control_bt_synonym varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ddt_control_id varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ddt_view_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, task_process_msg varchar(255) collate SQL_Latin1_General_CP1_CI_AS) 
create table #fw_req_ilbo_pivot_fields(component_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, activity_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ilbocode varchar(60) collate SQL_Latin1_General_CP1_CI_AS, PageName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, controlid varchar(60) collate SQL_Latin1_General_CP1_CI_AS, viewname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, rowlabel varchar(5) collate SQL_Latin1_General_CP1_CI_AS, columnlabel varchar(5) collate SQL_Latin1_General_CP1_CI_AS, fieldValue varchar(5) collate SQL_Latin1_General_CP1_CI_AS, rowlabelseq int,columnlabelseq int, valueseq int, ValueFunction varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
create table #de_published_ui_control_association_map(component_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, activity_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ilbocode varchar(60) collate SQL_Latin1_General_CP1_CI_AS, PageName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, section_bt_synonym  varchar(60) collate SQL_Latin1_General_CP1_CI_AS, controlid varchar(60) collate SQL_Latin1_General_CP1_CI_AS, viewname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, PropertyName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, PropertyControl varchar(60) collate SQL_Latin1_General_CP1_CI_AS, PropertyViewName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, TaskName varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
create table #de_published_subscription_dataitem(component_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, activity_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ilbocode varchar(60) collate SQL_Latin1_General_CP1_CI_AS, PageName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, TaskName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, subscribed_bt_synonym varchar(60) collate SQL_Latin1_General_CP1_CI_AS, controlid varchar(60) collate SQL_Latin1_General_CP1_CI_AS, viewname varchar(60) collate SQL_Latin1_General_CP1_CI_AS, Qlik_dataitem varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
create table #de_fw_des_publish_task_callout(component_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, activity_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ui_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, task_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS,  CalloutName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, CalloutMode varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
create table #de_fw_des_publish_task_callout_segement(component_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, activity_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ui_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, task_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS,  CalloutName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, SegmentName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, InstanceFlag int, SegmentSequence int, SegmentFlowAttribute varchar(10) collate SQL_Latin1_General_CP1_CI_AS) 
create table #de_fw_des_publish_task_callout_dataitem(component_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, activity_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ui_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS, task_name varchar(60) collate SQL_Latin1_General_CP1_CI_AS,  CalloutName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, SegmentName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, DataItemName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, FlowAttribute int, ControlID  varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ViewName varchar(60) collate SQL_Latin1_General_CP1_CI_AS) 
Create table #fw_des_publish_api_activity_ilbo_task( activityname varchar(60) collate SQL_Latin1_General_CP1_CI_AS,  ilbocode varchar(200) collate SQL_Latin1_General_CP1_CI_AS, taskname varchar(100) collate SQL_Latin1_General_CP1_CI_AS, SequenceNo          INT,SpecID          INT,SpecName                VARCHAR(300) collate SQL_Latin1_General_CP1_CI_AS,Version INT,Path              VARCHAR(500) collate SQL_Latin1_General_CP1_CI_AS,OperationVerb VARCHAR(10) collate SQL_Latin1_General_CP1_CI_AS,OperationID                VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS    ) 
 
CREATE TABLE #fw_des_publish_api_request_serv_map (              ServiceName     VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS,SectionName   VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS,SequenceNo                int,SpecID           INT,SpecName VARCHAR(300) collate SQL_Latin1_General_CP1_CI_AS,Version   int, Path                VARCHAR(500) collate SQL_Latin1_General_CP1_CI_AS,OperationVerb VARCHAR(5) collate SQL_Latin1_General_CP1_CI_AS, MediaType VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS,ParentSchemaName VARCHAR(100) collate SQL_Latin1_General_CP1_CI_AS,SchemaName VARCHAR(100) collate SQL_Latin1_General_CP1_CI_AS,SchemaCategory            VARCHAR(5) collate SQL_Latin1_General_CP1_CI_AS, SegmentName VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS, DataItemName     VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS,NodeID              NVARCHAR(MAX) collate SQL_Latin1_General_CP1_CI_AS,                ParentNodeID   NVARCHAR(MAX) collate SQL_Latin1_General_CP1_CI_AS,Identifier       VARCHAR(20) collate SQL_Latin1_General_CP1_CI_AS, Type   VARCHAR(20) collate SQL_Latin1_General_CP1_CI_AS, DisplayName       NVARCHAR(MAX) collate SQL_Latin1_General_CP1_CI_AS, SchemaType VARCHAR(100) collate SQL_Latin1_General_CP1_CI_AS)
CREATE TABLE #fw_des_publish_api_response_serv_map            (              ServiceName  VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS, SectionName  VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS, SequenceNo  int, SpecID            INT, SpecName  VARCHAR(300) collate SQL_Latin1_General_CP1_CI_AS, Version                int, Path                  VARCHAR(500) collate SQL_Latin1_General_CP1_CI_AS, OperationVerb VARCHAR(5) collate SQL_Latin1_General_CP1_CI_AS, MediaType  VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS, ResponseCode                VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS, ParentSchemaName VARCHAR(100) collate SQL_Latin1_General_CP1_CI_AS, SchemaName  VARCHAR(100) collate SQL_Latin1_General_CP1_CI_AS, SchemaCategory              VARCHAR(5) collate SQL_Latin1_General_CP1_CI_AS, SegmentName  VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS, DataItemName              VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS, NodeID                  NVARCHAR(MAX) collate SQL_Latin1_General_CP1_CI_AS, ParentNodeID            NVARCHAR(MAX) collate SQL_Latin1_General_CP1_CI_AS, Identifier            VARCHAR(20) collate SQL_Latin1_General_CP1_CI_AS,Type                VARCHAR(20) collate SQL_Latin1_General_CP1_CI_AS,DisplayName        NVARCHAR(MAX) collate SQL_Latin1_General_CP1_CI_AS, SchemaType VARCHAR(100) collate SQL_Latin1_General_CP1_CI_AS)
CREATE TABLE #fw_des_publish_api_pathparameter_serv_map (ServiceName VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS, SectionName VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS, SequenceNo int, SpecID           INT, SpecName VARCHAR(300) collate SQL_Latin1_General_CP1_CI_AS, Version int, Path                 VARCHAR(500) collate SQL_Latin1_General_CP1_CI_AS,  ParameterName             VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS, SegmentName VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS, DataItemName VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS, [In] VARCHAR(50) collate SQL_Latin1_General_CP1_CI_AS)
CREATE TABLE #fw_des_publish_api_pathoperationparameter_serv_map (ServiceName VARCHAR(60), SectionName VARCHAR(60), SequenceNo int, SpecID INT, SpecName VARCHAR(300) collate SQL_Latin1_General_CP1_CI_AS, Version      int, Path  VARCHAR(500) collate SQL_Latin1_General_CP1_CI_AS,  OperationVerb      VARCHAR(60), ParameterName VARCHAR(60), SegmentName VARCHAR(60), DataItemName  VARCHAR(60), [In] VARCHAR(50) collate SQL_Latin1_General_CP1_CI_AS)
CREATE TABLE #fw_des_upe_control_task_detail              (ComponentName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ActivityName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UIName varchar(60) collate SQL_Latin1_General_CP1_CI_AS,       TaskName           VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS,TaskType           VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS,MoreAction                VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS,SetFocus VARCHAR(300) collate SQL_Latin1_General_CP1_CI_AS, ServiceName  VARCHAR(500) collate SQL_Latin1_General_CP1_CI_AS,ProcessSection VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS, SectionSequence VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS,MethodID VARCHAR(100) collate SQL_Latin1_General_CP1_CI_AS,MethodName VARCHAR(100) collate SQL_Latin1_General_CP1_CI_AS,MethodSequence          VARCHAR(5) collate SQL_Latin1_General_CP1_CI_AS, ControlName VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS, ViewName VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS,ControlType     VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS,dependencyorder          VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS,triggeringcontrolid  VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS,triggeringviewname VARCHAR(60) collate SQL_Latin1_General_CP1_CI_AS         )
create table #fw_des_els_query_ps_result (servicename varchar(64) collate SQL_Latin1_General_CP1_CI_AS, ProcessSectionName varchar(64) collate SQL_Latin1_General_CP1_CI_AS , ProcessSectionSeq int  , segmentname varchar(60) collate SQL_Latin1_General_CP1_CI_AS ,  dataitemname varchar(60) collate SQL_Latin1_General_CP1_CI_AS)
 
 
CREATE TABLE #fw_des_publish_task_api_mapping    (ComponentName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ActivityName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UIName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, TaskName    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS,    TaskType    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, ApiExecSequence    INT, ApiSpecID    INT, ApiSpecName    VARCHAR(300) COLLATE SQL_Latin1_General_CP1_CI_AS, ApiVersion    INT, ApiPath    VARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS, ApiOperationVerb        VARCHAR(5) COLLATE SQL_Latin1_General_CP1_CI_AS, ApiOperationID    VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS )
CREATE TABLE #fw_des_publish_subtask    (ComponentName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ActivityName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UIName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, TaskName    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, TaskType    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, SubTaskName    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, SubTaskType    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, SubTaskSequence    INT )
CREATE TABLE #fw_des_publish_task_api_parameter_map    (ComponentName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ActivityName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UIName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, TaskName    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, ApiExecSequence    INT, ApiSpecID    INT, ApiSpecName    VARCHAR(300) COLLATE SQL_Latin1_General_CP1_CI_AS, ApiVersion    INT, ApiPath    VARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS, ApiOperationVerb        VARCHAR(5) COLLATE SQL_Latin1_General_CP1_CI_AS, ApiOperationID    VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS, ParameterName    VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS, ParameterLocation    VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS, ParameterType    VARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS, Identifier    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, DataType    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, SchemaMemberLevel    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, IsPrimitiveType    VARCHAR(5) COLLATE SQL_Latin1_General_CP1_CI_AS, IsMandatory    VARCHAR(5) COLLATE SQL_Latin1_General_CP1_CI_AS, ConstantValue    VARCHAR(2000) COLLATE SQL_Latin1_General_CP1_CI_AS, ControlID    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, ViewName    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, BTSynonymName    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, ControlDataType    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, NodeID    VARCHAR(2000) COLLATE SQL_Latin1_General_CP1_CI_AS, ParentNodeID VARCHAR(2000) COLLATE SQL_Latin1_General_CP1_CI_AS )
CREATE TABLE #fw_des_publish_task_api_request_map    (ComponentName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ActivityName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UIName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, TaskName    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, ApiExecSequence    INT, ApiSpecID    INT, ApiSpecName    VARCHAR(300) COLLATE SQL_Latin1_General_CP1_CI_AS, ApiVersion    INT, ApiPath    VARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS, ApiOperationVerb        VARCHAR(5) COLLATE SQL_Latin1_General_CP1_CI_AS, ApiOperationID    VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS, MediaType    VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS, ParentSchemaName    VARCHAR(300) COLLATE SQL_Latin1_General_CP1_CI_AS, SchemaName    VARCHAR(300) COLLATE SQL_Latin1_General_CP1_CI_AS, FlattenedSchemaName    VARCHAR(300) COLLATE SQL_Latin1_General_CP1_CI_AS, Identifier    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, DataType    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, SchemaType    VARCHAR(300) COLLATE SQL_Latin1_General_CP1_CI_AS, SchemaCategory    VARCHAR(300) COLLATE SQL_Latin1_General_CP1_CI_AS, SchemaMemberLevel    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, IsPrimitiveType    VARCHAR(5) COLLATE SQL_Latin1_General_CP1_CI_AS, IsMandatory    VARCHAR(5) COLLATE SQL_Latin1_General_CP1_CI_AS, ConstantValue    VARCHAR(2000) COLLATE SQL_Latin1_General_CP1_CI_AS, ControlID    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, ViewName    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, BTSynonymName    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, ControlDataType    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, ProcessingType VARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS, NodeID    VARCHAR(2000) COLLATE SQL_Latin1_General_CP1_CI_AS, ParentNodeID VARCHAR(2000) COLLATE SQL_Latin1_General_CP1_CI_AS )
CREATE TABLE #fw_des_publish_task_api_response_map    (ComponentName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, ActivityName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, UIName varchar(60) collate SQL_Latin1_General_CP1_CI_AS, TaskName    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, ApiExecSequence    INT, ControlID    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, ViewName    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, BTSynonymName    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, ControlDataType    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, ApiSpecID    INT, ApiSpecName    VARCHAR(300) COLLATE SQL_Latin1_General_CP1_CI_AS, ApiVersion    INT, ApiPath    VARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS, ApiOperationVerb        VARCHAR(5) COLLATE SQL_Latin1_General_CP1_CI_AS, ApiOperationID    VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS, MediaType    VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS, ParentSchemaName    VARCHAR(300) COLLATE SQL_Latin1_General_CP1_CI_AS, SchemaName    VARCHAR(300) COLLATE SQL_Latin1_General_CP1_CI_AS, FlattenedSchemaName    VARCHAR(300) COLLATE SQL_Latin1_General_CP1_CI_AS, Identifier    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, DataType    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, SchemaType    VARCHAR(300) COLLATE SQL_Latin1_General_CP1_CI_AS, SchemaCategory    VARCHAR(300) COLLATE SQL_Latin1_General_CP1_CI_AS, SchemaMemberLevel    VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS, IsPrimitiveType    VARCHAR(5) COLLATE SQL_Latin1_General_CP1_CI_AS, IsMandatory    VARCHAR(5) COLLATE SQL_Latin1_General_CP1_CI_AS, ConstantValue    VARCHAR(2000) COLLATE SQL_Latin1_General_CP1_CI_AS,   NodeID    VARCHAR(2000) COLLATE SQL_Latin1_General_CP1_CI_AS, ParentNodeID VARCHAR(2000) COLLATE SQL_Latin1_General_CP1_CI_AS )
 
exec vw_netgen_populate_temptable_sp            @customername = @lcustomername,
                                                                                                                                                                @projectname = @lprojectname,
                                                                                                                                                                @componentname = @lcomponentname,
                                                                                                                                                                @ecrno = @lecrno
 
 
--exec vw_netgen_activityschema_taskapi_sp @lcustomername,@lprojectname,@lecrno,@lcomponentname,@lguid
 
 
exec vw_netgen_activityschema_sp_attachtest 
                                                                                                                                                @customer_name = @lcustomername,
                                                                                                                                                @project_name = @lprojectname,
                                                                                                                                                @ecrno = @lecrno,
                                                                                                                                                @component_name= @lcomponentname,
                                                                                                                                                @guid = @lguid 
 
----exec vw_netgen_errorschema_sp @componentname = @lcomponentname, @langid = '1'
 
--exec vw_netgen_serviceschema_sp @guid=@lguid,@EcrNo=@lecrno
 
rollback

